sonata_admin:
    title: 'DEV CMS'
#    title_logo: ''

    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

    security:
      handler: sonata.admin.security.handler.acl
      role_admin: ROLE_ADMIN
      role_super_admin: ROLE_SUPER_ADMIN

      # acl security information
      information:
        GUEST: [ VIEW, LIST ]
        STAFF: [ EDIT, LIST, CREATE ]
        EDITOR: [ OPERATOR, EXPORT ]
        ADMIN: [ MASTER ]

      # permissions not related to an object instance and also to be available when objects do not exist
      # the DELETE admin permission means the user is allowed to batch delete objects
      admin_permissions: [ CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER ]

      # permission related to the objects
      object_permissions: [ VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER ]

    options:
        legacy_twig_text_extension: false
        title_mode: single_text

    assets:
        extra_stylesheets:
          - bundles/sonatatranslation/css/sonata-translation.css
          - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-blue.min.css

    templates:
        layout: adminOverrides/adminLayout.html.twig
        edit: adminOverrides/edit.html.twig
#        list: adminOverrides/list.html.twig


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
